import '../styles/globals.scss'
import { AppProps } from "next/dist/shared/lib/router/router"
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
    return <>
        <Head>
          <title>MyStore</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@300;400;500;700&display=swap"
                rel="stylesheet"/>
        </Head>
        <Component {...pageProps} />
    </>
}

export default MyApp
